### PR TITLE
Chap5 Model View Architecture Advanced

### PR DESCRIPTION
**Pull request by EricoDeMecha**
- Updated lectures in chapter 5 to Qt6 while maintaining backward compatibility.  
- Big changes are documented in the README file of a lecture.

### CODE REVIEW

**Comment by rutura** [comment]
"while maintaining backward compatibility.". There's no need to keep compatibility with Qt 5 here. In this updated course, we'll expect students to have an active Qt 6 installation.

**Comment by rutura** [comment]
Also, I would recommend updating the code in order from the beginning. That way, later projects benefit from the lessons learnt in earlier ones. We decided to update all lectures in the project anyway.

**Comment by EricoDeMecha** [comment]
Okay.

**Comment by rutura** [comment]
Lecture 5-8 Fails to compile with the error below: 
```
build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug --target all
[1/2 1.0/sec] Building CXX object CMakeFiles/5-8CustomModelsEditableWithHeadersDemo.dir/2c7fc4ea7847f62d7d81bb80f0ebbe71/mocs_compilation.cpp.obj
FAILED: CMakeFiles/5-8CustomModelsEditableWithHeadersDemo.dir/2c7fc4ea7847f62d7d81bb80f0ebbe71/mocs_compilation.cpp.obj 
C:\Qt\Tools\mingw1120_64\bin\g++.exe -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NEEDS_QMAIN -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -ID:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-8CustomModelsEditableWithHeadersDemo_autogen/include -isystem C:/Qt/6.6.1/mingw_64/include/QtCore -isystem C:/Qt/6.6.1/mingw_64/include -isystem C:/Qt/6.6.1/mingw_64/mkspecs/win32-g++ -isystem C:/Qt/6.6.1/mingw_64/include/QtWidgets -isystem C:/Qt/6.6.1/mingw_64/include/QtGui -DQT_QML_DEBUG -g -std=gnu++17 -fdiagnostics-color=always -MD -MT CMakeFiles/5-8CustomModelsEditableWithHeadersDemo.dir/2c7fc4ea7847f62d7d81bb80f0ebbe71/mocs_compilation.cpp.obj -MF CMakeFiles\5-8CustomModelsEditableWithHeadersDemo.dir\2c7fc4ea7847f62d7d81bb80f0ebbe71\mocs_compilation.cpp.obj.d -o CMakeFiles/5-8CustomModelsEditableWithHeadersDemo.dir/2c7fc4ea7847f62d7d81bb80f0ebbe71/mocs_compilation.cpp.obj -c D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-8CustomModelsEditableWithHeadersDemo_autogen/mocs_compilation.cpp
In file included from C:/Qt/6.6.1/mingw_64/include/QtCore/qtcoreexports.h:7,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qglobal.h:26,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qnamespace.h:12,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qobjectdefs.h:12,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qobject.h:10,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/QObject:1,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/5-8CustomModelsEditableWithHeadersDemo/person.h:4,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-8CustomModelsEditableWithHeadersDemo_autogen/EWIEGA46WW/moc_person.cpp:9,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-8CustomModelsEditableWithHeadersDemo_autogen/mocs_compilation.cpp:2:
D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-8CustomModelsEditableWithHeadersDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-8CustomModelsEditableWithHeadersDemo_autogen/EWIEGA46WW/moc_widget.cpp:115:1: fatal error: opening dependency file CMakeFiles\5-8CustomModelsEditableWithHeadersDemo.dir\2c7fc4ea7847f62d7d81bb80f0ebbe71\mocs_compilation.cpp.obj.d: No such file or directory
  115 | QT_WARNING_POP
      | ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
09:13:31: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 1.
Error while building/deploying project 5-8CustomModelsEditableWithHeadersDemo (kit: Desktop Qt 6.6.1 MinGW 64-bit)
When executing step "Build"
```

**Comment by rutura** [comment]
Lecture 5-10 fails to compile with the error below: 
```
1/7 1.7/sec] Automatic MOC and UIC for target 5-10CustomModelsCustomRolesDemo
[2/7 1.4/sec] Building CXX object CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/person.cpp.obj
[3/7 1.7/sec] Building CXX object CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/8588e12f9ae5bed5a176f307b2969b94/mocs_compilation.cpp.obj
FAILED: CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/8588e12f9ae5bed5a176f307b2969b94/mocs_compilation.cpp.obj 
C:\Qt\Tools\mingw1120_64\bin\g++.exe -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NEEDS_QMAIN -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -ID:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-10CustomModelsCustomRolesDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-10CustomModelsCustomRolesDemo_autogen/include -isystem C:/Qt/6.6.1/mingw_64/include/QtCore -isystem C:/Qt/6.6.1/mingw_64/include -isystem C:/Qt/6.6.1/mingw_64/mkspecs/win32-g++ -isystem C:/Qt/6.6.1/mingw_64/include/QtWidgets -isystem C:/Qt/6.6.1/mingw_64/include/QtGui -DQT_QML_DEBUG -g -std=gnu++17 -fdiagnostics-color=always -MD -MT CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/8588e12f9ae5bed5a176f307b2969b94/mocs_compilation.cpp.obj -MF CMakeFiles\5-10CustomModelsCustomRolesDemo.dir\8588e12f9ae5bed5a176f307b2969b94\mocs_compilation.cpp.obj.d -o CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/8588e12f9ae5bed5a176f307b2969b94/mocs_compilation.cpp.obj -c D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-10CustomModelsCustomRolesDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-10CustomModelsCustomRolesDemo_autogen/mocs_compilation.cpp
In file included from C:/Qt/6.6.1/mingw_64/include/QtCore/qtcoreexports.h:7,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qglobal.h:26,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qnamespace.h:12,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qobjectdefs.h:12,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/qobject.h:10,
                 from C:/Qt/6.6.1/mingw_64/include/QtCore/QObject:1,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/5-10CustomModelsCustomRolesDemo/person.h:4,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-10CustomModelsCustomRolesDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-10CustomModelsCustomRolesDemo_autogen/EWIEGA46WW/moc_person.cpp:9,
                 from D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-10CustomModelsCustomRolesDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-10CustomModelsCustomRolesDemo_autogen/mocs_compilation.cpp:2:
D:/Sandbox/Qt-5-C-GUI-Development-Intermediate/Chap5-ModelViewArchitectureAdvanced/build-5-10CustomModelsCustomRolesDemo-Desktop_Qt_6_6_1_MinGW_64_bit-Debug/5-10CustomModelsCustomRolesDemo_autogen/EWIEGA46WW/moc_widget.cpp:156:1: fatal error: opening dependency file CMakeFiles\5-10CustomModelsCustomRolesDemo.dir\8588e12f9ae5bed5a176f307b2969b94\mocs_compilation.cpp.obj.d: No such file or directory
  156 | QT_WARNING_POP
      | ^~~~~~~~~~~~~~
compilation terminated.
[4/7 2.2/sec] Building CXX object CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/main.cpp.obj
[5/7 2.7/sec] Building CXX object CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/personmodel.cpp.obj
[6/7 3.2/sec] Building CXX object CMakeFiles/5-10CustomModelsCustomRolesDemo.dir/widget.cpp.obj
ninja: build stopped: subcommand failed.
09:18:42: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 1.
Error while building/deploying project 5-10CustomModelsCustomRolesDemo (kit: Desktop Qt 6.6.1 MinGW 64-bit)
```

**Comment by rutura** [comment]
Lecture 5-11 fails to compile with the same error

**Comment by rutura** [comment]
Lecture 5-13 fails to compile with the same error.

**Comment by rutura** [comment]
Lecture 5-17-2 fails to compile with the same error.

**Comment by rutura** [comment]
Lecture 5-20 fails to compile with the same error.

**Comment by EricoDeMecha** [comment]
Compiles well on debian-linux. Let  me setup and test on windows.

**Pull request closed without merging**
